apiVersion: v1
kind: Secret
metadata:
  name: inventory-db-secret
  namespace: movie-platform
type: Opaque
stringData:
  POSTGRES_DB: inventory_db
  POSTGRES_USER: m
  POSTGRES_PASSWORD: "1234"
# stringData lets you write plain text;
#  Kubernetes will store it as base64.