apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: movie-platform
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: rabbituser
  RABBITMQ_DEFAULT_PASS: rabbitpassword

  # Used by billing-app
  AMQP_URL: amqp://rabbituser:rabbitpassword@rabbitmq:5672
  RABBIT_QUEUE: billing-queue
